# Generated by Django 4.2.15 on 2026-06-07 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('match', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('team_kills', models.IntegerField()),
                ('kills', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('cs', models.IntegerField()),
                ('damage_dealt', models.IntegerField()),
                ('vision_score', models.IntegerField()),
                ('kill_participation', models.FloatField()),
                ('obj_secured', models.IntegerField()),
                ('first_item', models.CharField(max_length=50)),
                ('early_tempo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FocusConcepts',
            fields=[
                ('concept', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('win_rate', models.FloatField()),
                ('very_good_rate', models.FloatField()),
                ('good_rate', models.FloatField()),
                ('okay_rate', models.FloatField()),
                ('bad_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FocusCycles',
            fields=[
                ('start_date', models.DateField(primary_key=True, serialize=False)),
                ('improvement_focus', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('match', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('cs_per_min', models.FloatField()),
                ('vision_per_min', models.FloatField()),
                ('damage_per_min', models.FloatField()),
                ('gold_delta_10', models.IntegerField()),
                ('xp_delta_10', models.IntegerField()),
                ('cs_delta_10', models.IntegerField()),
                ('ka_delta_10', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('match', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('gameplan', models.CharField(max_length=100)),
                ('major_mistake', models.CharField(max_length=100)),
                ('mental', models.CharField(max_length=20)),
                ('focus_rating', models.IntegerField()),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tempo',
            fields=[
                ('match', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('gold_10', models.IntegerField()),
                ('enemy_gold_10', models.IntegerField()),
                ('xp_10', models.IntegerField()),
                ('enemy_xp_10', models.IntegerField()),
                ('cs_10', models.IntegerField()),
                ('enemy_cs_10', models.IntegerField()),
                ('ka_10', models.IntegerField()),
                ('enemy_ka_10', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WeeklySummary',
            fields=[
                ('week', models.AutoField(primary_key=True, serialize=False)),
                ('games', models.IntegerField()),
                ('win_rate', models.FloatField()),
                ('average_deaths', models.FloatField()),
                ('average_obj', models.FloatField()),
                ('good_tempo', models.FloatField()),
                ('bad_tempo', models.FloatField()),
                ('tilt_percent', models.FloatField()),
                ('start_rank', models.CharField(max_length=20)),
                ('start_lp', models.IntegerField()),
                ('end_rank', models.CharField(max_length=20)),
                ('end_lp', models.IntegerField()),
                ('lp_delta', models.IntegerField()),
            ],
        ),
    ]
