# Generated by Django 4.2.15 on 2026-06-07 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_details_focusconcepts_focuscycles_metrics_review_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='first_item',
            new_name='first_item_timing',
        ),
    ]
