# Generated by Django 4.2.15 on 2026-06-07 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_rename_first_item_details_first_item_timing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='gameplan',
            new_name='gameplan_adherence',
        ),
    ]
