# Generated by Django 4.2.15 on 2026-06-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_rename_gameplan_review_gameplan_adherence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='focus_rating',
            field=models.CharField(max_length=20),
        ),
    ]
