# Generated by Django 4.2.15 on 2026-06-07 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_alter_review_focus_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklysummary',
            old_name='games',
            new_name='games_played',
        ),
    ]
