services:
  backend:
    build:
      context: ./backend
    working_dir: /jil
    volumes:
      - ./backend/jil:/jil
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=jil.settings
    depends_on:
      - database
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    develop:
      watch:
        - path: ./frontend
          target: /frontend
          action: sync
    networks:
      - app-network

  database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: jil_db
      MYSQL_USER: jiluser
      MYSQL_PASSWORD: jilpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
