# Generated by Django 4.2.15 on 2026-06-07 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Overview',
            fields=[
                ('match', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('patch', models.CharField(max_length=20)),
                ('rank', models.CharField(max_length=20)),
                ('lp', models.IntegerField()),
                ('champion', models.CharField(max_length=20)),
                ('results', models.CharField(max_length=20)),
                ('length', models.CharField(max_length=20)),
            ],
        ),
    ]
